Tasks 1,2
maxtrukhanovich/small-tasks pull request #1
Opened 2021-09-12 21:46 UTC by maxtrukhanovich

По 1 таске все понятно.

Во второй не уверен, что я правильно делаю, когда в цикле

```
Rand rand = () => new Random().Next(0, 10);

for (var i = 0; i < delegatesArray.Length; i++)
{
    delegatesArray[i] = rand;
}
```

записываю значения в массив. Или тут все таки ссылка записывается?

2021-09-14 17:28 UTC, amonich requested changes

2021-09-14 17:28 UTC, amonich commented on Delegates/MathOperation.cs
> +                parameters[i] = parameters[i + 1];
сложноватая для восприятия конструкция
можно было проверить что inputArray.Length == 3 и если нет, то сразу написать что юзер ошибся
потом что то типа такого
```
            string command = parameters[0];
            int first = default(int);
            int second = default(int);

            if (!int.TryParse(parameters[1], out first) ||
                !int.TryParse(parameters[2], out second))
            {
                Console.WriteLine("какое-то сообщение");
                return;
            }
```

2021-09-14 17:28 UTC, amonich commented on Delegates/MathOperation.cs
> +            switch (command?.ToUpper())
создание переменной типа Operation лучше вынести до switch 

и после свича вызвать этот делегат один раз передав туда значение а результат вывести в консоль

2021-09-14 17:28 UTC, amonich commented on Delegates/MathOperation.cs
> +                    Operation div = (x, y) => y > 0 ? x / y : 0;
нужно использовать лямбда оператор (многострочный) чтоб проверка на 0 была в нем, и если ноль то выбрасывать исключение из него же, например такое https://docs.microsoft.com/ru-ru/dotnet/api/system.argumentexception?view=net-5.0

`y > 0` неверная проверка, можно делить на отрицательные числа
возвращать 0 тоже неправильно, если я разделю 0 на 10, то в консоли будет "Can't divide by 0"

2021-09-14 17:28 UTC, amonich commented on Delegates/MathOperation.cs
> +                        $"{(div(int.Parse(parameters[0]), int.Parse(parameters[1])) == 0 ? "Can't divide by 0." : "Result is " + div(int.Parse(parameters[0]), int.Parse(parameters[1])))}");
не нужно два раза одну и ту же функцию с теми же параметрами вызывать, бессмысленная трата процессорного времени, закэшируй результат вызова и дальше работай с ним

2021-09-14 17:28 UTC, amonich commented on Program.cs
> +                    task1.Operations();
метод лучше переименовать в что то типа Run, во первых методы именуются глаголами, за редким исключением, во вторых лучше отражает смысл, ты как бы выбираешь какое задание и запускаешь его

и было бы хорошо добавить интерфейс с методом Run (или как то иначе его назови, но со смыслом чтоб) и отнаследовать от него DelegatesArray и MathOperation, завести переменную этого типа интерфейса и в свиче только заполнять ее, а вызывать метод на ней уже после свича

Сейчас получается, что у тебя методы хоть и называются одинаково, но никак не связаны между собой в коде, хотя логически связаны
Свич не должен делать много работы в своих кейсах, как правило. Сейчас же ты в каждом кейсе создаешь объект нужного типа и вызываешь нужный метод на нем (как по мне много ответственности на свиче лежит), с добавлением интерфейса свич будет создавать экземпляр нужного типа и присваивать его переменной типа интерфейса, а вся работа с этой переменной уже не его забота

2021-09-14 22:55 UTC, maxtrukhanovich commented on Delegates/MathOperation.cs
> +                    Operation div = (x, y) => y > 0 ? x / y : 0;
Лямбда должна вернуть инт. Я сделал делегат nullable, в try возвращаю x / y, в catch сообщение, если exception и в самом конце налл возвращаю. Но после свича надо проверять не налл ли приходит и после этого вызывать Console.Write.

Можно это проще захэндлить?

2021-09-14 22:58 UTC, maxtrukhanovich commented
С массивом делегатов все правильно? Там было сложнее всего с осознанием того, что делаю.

2021-09-15 17:42 UTC, amonich commented
> По 1 таске все понятно.
> 
> Во второй не уверен, что я правильно делаю, когда в цикле
> 
> ```
> Rand rand = () => new Random().Next(0, 10);
> 
> for (var i = 0; i < delegatesArray.Length; i++)
> {
>     delegatesArray[i] = rand;
> }
> ```
> 
> записываю значения в массив. Или тут все таки ссылка записывается?



> По 1 таске все понятно.
> 
> Во второй не уверен, что я правильно делаю, когда в цикле
> 
> ```
> Rand rand = () => new Random().Next(0, 10);
> 
> for (var i = 0; i < delegatesArray.Length; i++)
> {
>     delegatesArray[i] = rand;
> }
> ```
> 
> записываю значения в массив. Или тут все таки ссылка записывается?

тут ссылка записывается, но это правильно, можно было новый экземпляр делегата создавать каждый раз, а можно так, если так то меньше памяти тратится

2021-09-15 17:43 UTC, amonich commented
> С массивом делегатов все правильно? Там было сложнее всего с осознанием того, что делаю.

да, там все хорошо

2021-09-15 17:47 UTC, amonich commented on Delegates/MathOperation.cs
> +                    Operation div = (x, y) => y > 0 ? x / y : 0;
В принципе сейчас норм, хотя я бы сам кидал исключение если y = 0
Но так как работу с исключениями еще не проходили можно и так

2021-09-15 17:47 UTC, amonich approved these changes
Можно мержить

2021-09-15 20:42 UTC, merged