Task 3
maxtrukhanovich/small-tasks pull request #2
Opened 2021-09-12 21:51 UTC by maxtrukhanovich

Я сразу хэндлеры создал как классы, потом в лямбды их загнал. Покритикуйте, пожалуйста. Общая идея событий понятна, но пока довольно абстрактно все.

2021-09-14 17:32 UTC, amonich commented on Stopwatch/HandlerNotify.cs
> +        public void Message(int seconds)
обработчики событий должны иметь следующую сигнатуру
`public delegate void EventHandler(object? sender, EventArgs e);`

2021-09-14 17:41 UTC, amonich requested changes

2021-09-14 17:41 UTC, amonich commented on Stopwatch/StopwatchApp.cs
> +        public delegate void MethodContainer(int second);
можешь использовать стандартные делегаты, либо написать свой, но с похожей сигнатурой

стандартных два, можешь попробовать второй, он generic, в примере который я скинул используется делегат похожий на первый тк дженерики были еще неведомы)
https://docs.microsoft.com/ru-ru/dotnet/api/system.eventhandler?view=net-5.0
https://docs.microsoft.com/ru-ru/dotnet/api/system.eventhandler-1?view=net-5.0

2021-09-14 17:41 UTC, amonich commented on Stopwatch/StopwatchApp.cs
> +                while (!Console.KeyAvailable)
не нужно здесь обрабатывать ввод с консоли, просто создай вечный счетчик, обычно объекты такого плана просто удаляют из памяти когда они не нужны, либо в них есть 2 метода Sart и Stop
но никак не внутри объекта это должно быть

2021-09-14 17:41 UTC, amonich commented on Stopwatch/StopwatchApp.cs
> +            stopwatch.OnCount += (eventArgs) =>
подписываться на событие нужно извне, а не внутри объекта, разбери внимательно пример который я скидывал, что то похожее должно быть

2021-09-16 17:44 UTC, maxtrukhanovich commented on Stopwatch/StopwatchApp.cs
> +                while (!Console.KeyAvailable)
Не понимаю, как извне класса Counter остановить while внутри метода класса Counter, поэтому пока, чтобы работало, завязал while на !Console.KeyAvailable.

2021-09-19 18:55 UTC, amonich commented on Stopwatch/StopwatchApp.cs
> +                while (!Console.KeyAvailable)
завязать ее на приватную переменную типа bool, которую ставить а false в методе Stop

2021-09-19 19:03 UTC, amonich requested changes

2021-09-19 19:03 UTC, amonich commented on Events/Counter.cs
> +                if (_counted == null) continue;
есть проблемка, наверное я на предыдущем ревью не заметил
из за этого условия у тебя не будет увеличиваться каунтер пока не появится хотя бы один подписчик на событии

главная идея событий в том что класс через них просто уведомляет о чем то, тех кто зяхотел подписаться на событие, но ни сам вызов событий ни наличие подписчиков не должно влиять на работу методов класса

2021-09-21 19:58 UTC, amonich reviewed
можно мержить

2021-09-21 19:59 UTC, amonich approved these changes

2021-09-21 20:55 UTC, merged